#############################################################################
# Makefile for building: all
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  all.pro
# Template: subdirs
# Command: C:\Users\sunlo\Anaconda3\Library\bin\qmake.exe -spec win32-msvc2013 -o Makefile all.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Users\sunlo\Anaconda3\Library\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-viewer \
		sub-plugins


sub-viewer-qmake_all:  FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	cd viewer\ && $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && $(MAKE) -f Makefile qmake_all
sub-viewer: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile
sub-viewer-make_first-ordered: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-viewer-make_first: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-viewer-all-ordered: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-viewer-all: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-viewer-clean-ordered: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-viewer-clean: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-viewer-distclean-ordered: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-viewer-distclean: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-viewer-install_subtargets-ordered: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-viewer-install_subtargets: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-viewer-uninstall_subtargets-ordered: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-viewer-uninstall_subtargets: FORCE
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-plugins-qmake_all: sub-viewer-qmake_all FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	cd plugins\ && $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && $(MAKE) -f Makefile qmake_all
sub-plugins: viewer-bin-libglwidget-so \
		viewer-bin-libglwidgetd-so \
		viewer-bin-libcore-so \
		viewer-bin-libcored-so FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile
sub-plugins-make_first-ordered: sub-viewer-make_first-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-plugins-make_first: viewer-bin-libglwidget-so-make_first viewer-bin-libglwidgetd-so-make_first viewer-bin-libcore-so-make_first viewer-bin-libcored-so-make_first FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-plugins-all-ordered: sub-viewer-all-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-plugins-all: viewer-bin-libglwidget-so-all viewer-bin-libglwidgetd-so-all viewer-bin-libcore-so-all viewer-bin-libcored-so-all FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-plugins-clean-ordered: sub-viewer-clean-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-plugins-clean: viewer-bin-libglwidget-so-clean viewer-bin-libglwidgetd-so-clean viewer-bin-libcore-so-clean viewer-bin-libcored-so-clean FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-plugins-distclean-ordered: sub-viewer-distclean-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-plugins-distclean: viewer-bin-libglwidget-so-distclean viewer-bin-libglwidgetd-so-distclean viewer-bin-libcore-so-distclean viewer-bin-libcored-so-distclean FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-plugins-install_subtargets-ordered: sub-viewer-install_subtargets-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-plugins-install_subtargets: viewer-bin-libglwidget-so-install_subtargets viewer-bin-libglwidgetd-so-install_subtargets viewer-bin-libcore-so-install_subtargets viewer-bin-libcored-so-install_subtargets FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-plugins-uninstall_subtargets-ordered: sub-viewer-uninstall_subtargets-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-plugins-uninstall_subtargets: viewer-bin-libglwidget-so-uninstall_subtargets viewer-bin-libglwidgetd-so-uninstall_subtargets viewer-bin-libcore-so-uninstall_subtargets viewer-bin-libcored-so-uninstall_subtargets FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: all.pro C:\Users\sunlo\Anaconda3\Library\mkspecs\win32-msvc2013\qmake.conf C:\Users\sunlo\Anaconda3\Library\mkspecs\features\spec_pre.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\common\angle.conf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\common\msvc-base.conf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\common\msvc-desktop.conf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\qconfig.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3drender.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axbase.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axserver.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_core.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_core_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_dbus.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_designer.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_enginio.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_enginio_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_gui.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_help.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_help_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_labscontrols_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_labstemplates_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_location.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_location_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_network.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_network_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_nfc.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_opengl.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_positioning.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qml.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_quick.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_script.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_script_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_sensors.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_serialport.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_sql.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_svg.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_testlib.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_uitools.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webkit.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webkit_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webkitwidgets.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webkitwidgets_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_websockets.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_widgets.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_winextras.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_xml.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\qt_functions.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\qt_config.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\win32\qt_config.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\win32-msvc2013\qmake.conf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\spec_post.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\exclusive_builds.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\default_pre.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\win32\default_pre.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\resolve_config.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\exclusive_builds_post.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\default_post.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\win32\rtti.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\precompile_header.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\warn_on.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\file_copies.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\win32\windows.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\testcase_targets.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\exceptions.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\yacc.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\lex.prf \
		C:\Users\sunlo\Anaconda3\Library\mkspecs\features\silent.prf \
		all.pro
	$(QMAKE) -spec win32-msvc2013 -o Makefile all.pro
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\spec_pre.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\common\angle.conf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\common\msvc-base.conf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\common\msvc-desktop.conf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\qconfig.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dcore.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dinput.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquick.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3drender.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axbase.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axserver.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_concurrent.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_core.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_core_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_dbus.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_designer.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_designer_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_enginio.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_enginio_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_gui.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_gui_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_help.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_help_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_labscontrols_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_labstemplates_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_location.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_location_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_multimedia.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_network.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_network_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_nfc.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_opengl.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_positioning.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_printsupport.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qml.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qml_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qmltest.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_quick.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_quick_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_script.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_script_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_scripttools.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_sensors.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_serialbus.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_serialport.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_sql.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_sql_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_svg.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_svg_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_testlib.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_uitools.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webchannel.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webkit.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webkit_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_websockets.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_widgets.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_winextras.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_xml.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_xml_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\qt_functions.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\qt_config.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\win32\qt_config.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\win32-msvc2013\qmake.conf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\spec_post.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\exclusive_builds.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\default_pre.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\win32\default_pre.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\resolve_config.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\exclusive_builds_post.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\default_post.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\win32\rtti.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\precompile_header.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\warn_on.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\file_copies.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\win32\windows.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\testcase_targets.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\exceptions.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\yacc.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\lex.prf:
C:\Users\sunlo\Anaconda3\Library\mkspecs\features\silent.prf:
all.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 -o Makefile all.pro

qmake_all: sub-viewer-qmake_all sub-plugins-qmake_all FORCE

make_first: sub-viewer-make_first-ordered sub-plugins-make_first-ordered  FORCE
all: sub-viewer-all-ordered sub-plugins-all-ordered  FORCE
clean: sub-viewer-clean-ordered sub-plugins-clean-ordered  FORCE
distclean: sub-viewer-distclean-ordered sub-plugins-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-viewer-install_subtargets-ordered sub-plugins-install_subtargets-ordered FORCE
uninstall_subtargets: sub-viewer-uninstall_subtargets-ordered sub-plugins-uninstall_subtargets-ordered FORCE

sub-viewer-debug_ordered:
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile debug
sub-plugins-debug_ordered: sub-viewer-debug_ordered 
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-viewer-debug_ordered sub-plugins-debug_ordered

sub-viewer-release_ordered:
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile release
sub-plugins-release_ordered: sub-viewer-release_ordered 
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile release
release: sub-viewer-release_ordered sub-plugins-release_ordered

sub-viewer-check_ordered:
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile check
sub-plugins-check_ordered: sub-viewer-check_ordered 
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile check
check: sub-viewer-check_ordered sub-plugins-check_ordered

sub-viewer-benchmark_ordered:
	@if not exist viewer\ mkdir viewer\ & if not exist viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd viewer\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\viewer\viewer.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-plugins-benchmark_ordered: sub-viewer-benchmark_ordered 
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) J:\Descargas\NewViewer_8522e9b\NewViewer_8522e9b\plugins\plugins.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile benchmark
benchmark: sub-viewer-benchmark_ordered sub-plugins-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

